"""Initial ORBIT schema.

The first revision creates the whole schema from the SQLAlchemy metadata, which
keeps the ~40 tables of the modular monolith in one reviewable place. Every
later change is a normal hand-written or autogenerated Alembic revision on top
of this baseline.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.models import Base
import app.models  # noqa: F401  (registers every table on the metadata)

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


#: Tables and columns that later revisions create. ``Base.metadata`` describes
#: the schema as it is *today*; creating all of it here would leave every later
#: migration colliding with tables that already exist on a fresh database.
LATER_TABLES = {
    # 0002
    "letter_numberings", "letterheads", "letter_sequences", "letter_templates", "letters",
    # 0004
    "leave_adjustments", "leave_policies", "saved_views", "project_checkins",
    "recurring_transactions",
    # 0005
    "monitors", "monitor_checks", "tickets", "monitor_incidents", "ticket_messages",
    # 0006
    "task_statuses", "integration_links", "external_issues",
}
LATER_COLUMNS = {
    "crm_deals": {"next_step", "next_step_due", "last_activity_at"},   # 0004
    "users": {"crm_company_id", "weekly_capacity_hours"},              # 0005
}


def _create_initial_schema(bind) -> None:
    """Create the schema as it stood at this revision, from the current models."""
    tables = [t for t in Base.metadata.tables.values() if t.name not in LATER_TABLES]
    Base.metadata.create_all(bind=bind, tables=tables)
    # Columns a later revision adds: drop them again (with their indexes and
    # foreign keys) so that revision finds the table the way it expects.
    for table, columns in LATER_COLUMNS.items():
        for column in sorted(columns):
            op.execute(f'ALTER TABLE {table} DROP COLUMN IF EXISTS {column} CASCADE')


def upgrade() -> None:
    bind = op.get_bind()
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "pg_trgm"')
    # pgvector is optional: enable it only when the image ships it, so future
    # embedding columns can be added without another infrastructure change.
    # (Probing pg_available_extensions avoids aborting the migration transaction
    # on images without the extension.)
    has_vector = bind.exec_driver_sql(
        "SELECT count(*) FROM pg_available_extensions WHERE name = 'vector'"
    ).scalar()
    if has_vector:
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    _create_initial_schema(bind)

    # Full-text search helpers used by the global search service.
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_projects_fts ON projects "
        "USING gin (to_tsvector('simple', coalesce(name, '') || ' ' || coalesce(description, '')))"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_tasks_fts ON tasks "
        "USING gin (to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(description, '')))"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_documents_fts ON documents "
        "USING gin (to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(content, '')))"
    )


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
