"""Initial ORBIT schema.

The first revision creates the whole schema from the SQLAlchemy metadata, which
keeps the ~40 tables of the modular monolith in one reviewable place. Every
later change is a normal hand-written or autogenerated Alembic revision on top
of this baseline.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.models import Base
import app.models  # noqa: F401  (registers every table on the metadata)

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    bind = op.get_bind()
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "pg_trgm"')
    # pgvector is optional: enable it only when the image ships it, so future
    # embedding columns can be added without another infrastructure change.
    # (Probing pg_available_extensions avoids aborting the migration transaction
    # on images without the extension.)
    has_vector = bind.exec_driver_sql(
        "SELECT count(*) FROM pg_available_extensions WHERE name = 'vector'"
    ).scalar()
    if has_vector:
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    Base.metadata.create_all(bind=bind)

    # Full-text search helpers used by the global search service.
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_projects_fts ON projects "
        "USING gin (to_tsvector('simple', coalesce(name, '') || ' ' || coalesce(description, '')))"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_tasks_fts ON tasks "
        "USING gin (to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(description, '')))"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_documents_fts ON documents "
        "USING gin (to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(content, '')))"
    )


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
