"""Secretariat: the letter register, letterheads, numbering and templates

Revision ID: 0d59d8084dc1
Revises: 0001_initial
Create Date: 2026-09-11 12:27:04.283154
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0002_letters'
down_revision: str | None = '0001_initial'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('letter_numberings',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('pattern', sa.String(length=200), nullable=False),
    sa.Column('prefix', sa.String(length=40), nullable=False),
    sa.Column('kind_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('calendar', sa.String(length=12), nullable=False),
    sa.Column('digits', sa.String(length=8), nullable=False),
    sa.Column('reset', sa.String(length=12), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('start_at', sa.Integer(), nullable=False),
    sa.Column('separator', sa.String(length=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_letter_numberings_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_letter_numberings'))
    )
    op.create_index(op.f('ix_letter_numberings_company_id'), 'letter_numberings', ['company_id'], unique=False)
    op.create_table('letterheads',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('org_name', sa.String(length=200), nullable=False),
    sa.Column('org_name_secondary', sa.String(length=200), nullable=True),
    sa.Column('org_subtitle', sa.String(length=200), nullable=True),
    sa.Column('logo_key', sa.String(length=500), nullable=True),
    sa.Column('logo_data_url', sa.Text(), nullable=True),
    sa.Column('header_html', sa.Text(), nullable=True),
    sa.Column('footer_html', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=400), nullable=True),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.Column('fax', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('website', sa.String(length=160), nullable=True),
    sa.Column('postal_code', sa.String(length=40), nullable=True),
    sa.Column('paper', sa.String(length=12), nullable=False),
    sa.Column('margin_top_mm', sa.Integer(), nullable=False),
    sa.Column('margin_bottom_mm', sa.Integer(), nullable=False),
    sa.Column('margin_x_mm', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=4), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('font_family', sa.String(length=120), nullable=False),
    sa.Column('font_size_pt', sa.Integer(), nullable=False),
    sa.Column('accent_color', sa.String(length=16), nullable=False),
    sa.Column('signature_data_url', sa.Text(), nullable=True),
    sa.Column('stamp_data_url', sa.Text(), nullable=True),
    sa.Column('show_qr', sa.Boolean(), nullable=False),
    sa.Column('show_page_numbers', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_letterheads_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_letterheads'))
    )
    op.create_index(op.f('ix_letterheads_company_id'), 'letterheads', ['company_id'], unique=False)
    op.create_table('letter_sequences',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('numbering_id', sa.UUID(), nullable=False),
    sa.Column('scope_key', sa.String(length=40), nullable=False),
    sa.Column('period_key', sa.String(length=20), nullable=False),
    sa.Column('next_value', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_letter_sequences_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['numbering_id'], ['letter_numberings.id'], name=op.f('fk_letter_sequences_numbering_id_letter_numberings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_letter_sequences')),
    sa.UniqueConstraint('numbering_id', 'scope_key', 'period_key', name='uq_letter_sequences_numbering_id')
    )
    op.create_index(op.f('ix_letter_sequences_company_id'), 'letter_sequences', ['company_id'], unique=False)
    op.create_index(op.f('ix_letter_sequences_numbering_id'), 'letter_sequences', ['numbering_id'], unique=False)
    op.create_table('letter_templates',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=True),
    sa.Column('salutation', sa.String(length=300), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('closing', sa.String(length=300), nullable=True),
    sa.Column('letterhead_id', sa.UUID(), nullable=True),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_letter_templates_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_letter_templates_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['letterhead_id'], ['letterheads.id'], name=op.f('fk_letter_templates_letterhead_id_letterheads'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_letter_templates'))
    )
    op.create_index(op.f('ix_letter_templates_company_id'), 'letter_templates', ['company_id'], unique=False)
    op.create_table('letters',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(length=80), nullable=True),
    sa.Column('number_seq', sa.Integer(), nullable=True),
    sa.Column('number_period', sa.String(length=20), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('confidentiality', sa.String(length=20), nullable=False),
    sa.Column('urgency', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('salutation', sa.String(length=300), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('closing', sa.String(length=300), nullable=True),
    sa.Column('letter_date', sa.Date(), nullable=False),
    sa.Column('recipient_name', sa.String(length=200), nullable=True),
    sa.Column('recipient_title', sa.String(length=200), nullable=True),
    sa.Column('recipient_org', sa.String(length=200), nullable=True),
    sa.Column('recipient_address', sa.String(length=400), nullable=True),
    sa.Column('recipient_user_id', sa.UUID(), nullable=True),
    sa.Column('crm_company_id', sa.UUID(), nullable=True),
    sa.Column('cc', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sender_name', sa.String(length=200), nullable=True),
    sa.Column('sender_title', sa.String(length=200), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('signer_id', sa.UUID(), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_method', sa.String(length=20), nullable=True),
    sa.Column('in_reply_to_id', sa.UUID(), nullable=True),
    sa.Column('follow_up_of', sa.String(length=80), nullable=True),
    sa.Column('attachment_note', sa.String(length=200), nullable=True),
    sa.Column('letterhead_id', sa.UUID(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pdf_key', sa.String(length=500), nullable=True),
    sa.Column('docx_key', sa.String(length=500), nullable=True),
    sa.Column('rendered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_letters_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_letters_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['crm_company_id'], ['crm_companies.id'], name=op.f('fk_letters_crm_company_id_crm_companies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['in_reply_to_id'], ['letters.id'], name=op.f('fk_letters_in_reply_to_id_letters'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['letterhead_id'], ['letterheads.id'], name=op.f('fk_letters_letterhead_id_letterheads'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_letters_project_id_projects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], name=op.f('fk_letters_recipient_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['signer_id'], ['users.id'], name=op.f('fk_letters_signer_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['letter_templates.id'], name=op.f('fk_letters_template_id_letter_templates'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_letters')),
    sa.UniqueConstraint('company_id', 'number', name='uq_letters_company_id')
    )
    op.create_index(op.f('ix_letters_author_id'), 'letters', ['author_id'], unique=False)
    op.create_index(op.f('ix_letters_company_id'), 'letters', ['company_id'], unique=False)
    op.create_index('ix_letters_company_kind_status', 'letters', ['company_id', 'kind', 'status'], unique=False)
    op.create_index(op.f('ix_letters_crm_company_id'), 'letters', ['crm_company_id'], unique=False)
    op.create_index(op.f('ix_letters_in_reply_to_id'), 'letters', ['in_reply_to_id'], unique=False)
    op.create_index(op.f('ix_letters_kind'), 'letters', ['kind'], unique=False)
    op.create_index(op.f('ix_letters_number'), 'letters', ['number'], unique=False)
    op.create_index(op.f('ix_letters_project_id'), 'letters', ['project_id'], unique=False)
    op.create_index(op.f('ix_letters_status'), 'letters', ['status'], unique=False)
    # ### end Alembic commands ###

    # Letters join global search on the same footing as documents and tasks.
    op.execute(
        "CREATE INDEX ix_letters_fts ON letters USING gin ("
        "to_tsvector('simple', coalesce(subject,'') || ' ' || coalesce(number,'')"
        " || ' ' || coalesce(body,'') || ' ' || coalesce(recipient_name,'')"
        " || ' ' || coalesce(recipient_org,'')))"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_letters_fts")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_letters_status'), table_name='letters')
    op.drop_index(op.f('ix_letters_project_id'), table_name='letters')
    op.drop_index(op.f('ix_letters_number'), table_name='letters')
    op.drop_index(op.f('ix_letters_kind'), table_name='letters')
    op.drop_index(op.f('ix_letters_in_reply_to_id'), table_name='letters')
    op.drop_index(op.f('ix_letters_crm_company_id'), table_name='letters')
    op.drop_index('ix_letters_company_kind_status', table_name='letters')
    op.drop_index(op.f('ix_letters_company_id'), table_name='letters')
    op.drop_index(op.f('ix_letters_author_id'), table_name='letters')
    op.drop_table('letters')
    op.drop_index(op.f('ix_letter_templates_company_id'), table_name='letter_templates')
    op.drop_table('letter_templates')
    op.drop_index(op.f('ix_letter_sequences_numbering_id'), table_name='letter_sequences')
    op.drop_index(op.f('ix_letter_sequences_company_id'), table_name='letter_sequences')
    op.drop_table('letter_sequences')
    op.drop_index(op.f('ix_letterheads_company_id'), table_name='letterheads')
    op.drop_table('letterheads')
    op.drop_index(op.f('ix_letter_numberings_company_id'), table_name='letter_numberings')
    op.drop_table('letter_numberings')
    # ### end Alembic commands ###
