"""Letterhead banner images: wide header and footer stationery

Revision ID: fdff989ecb74
Revises: 0002_letters
Create Date: 2026-09-11 16:55:18.283111
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0003_letterhead_banners'
down_revision: str | None = '0002_letters'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('letterheads', sa.Column('header_image_data_url', sa.Text(), nullable=True))
    op.add_column('letterheads', sa.Column('footer_image_data_url', sa.Text(), nullable=True))
    op.add_column('letterheads', sa.Column('header_image_height_mm', sa.Integer(), nullable=False, server_default='26'))
    op.add_column('letterheads', sa.Column('footer_image_height_mm', sa.Integer(), nullable=False, server_default='16'))
    op.add_column('letterheads', sa.Column('header_image_full_bleed', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('letterheads', 'header_image_full_bleed')
    op.drop_column('letterheads', 'footer_image_height_mm')
    op.drop_column('letterheads', 'header_image_height_mm')
    op.drop_column('letterheads', 'footer_image_data_url')
    op.drop_column('letterheads', 'header_image_data_url')
    # ### end Alembic commands ###
