"""Saved views, project check-ins, CRM next steps, leave policy, recurring money

Revision ID: bf88434abc9c
Revises: 0003_letterhead_banners
Create Date: 2026-09-11 21:58:03.330258
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0004_daily_loops'
down_revision: str | None = '0003_letterhead_banners'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_adjustments',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('leave_type', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('days', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_leave_adjustments_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_leave_adjustments_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_leave_adjustments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_adjustments'))
    )
    op.create_index(op.f('ix_leave_adjustments_company_id'), 'leave_adjustments', ['company_id'], unique=False)
    op.create_index(op.f('ix_leave_adjustments_user_id'), 'leave_adjustments', ['user_id'], unique=False)
    op.create_table('leave_policies',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('leave_type', sa.String(length=20), nullable=False),
    sa.Column('annual_days', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('max_carryover', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('accrues_monthly', sa.Boolean(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_leave_policies_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_policies')),
    sa.UniqueConstraint('company_id', 'leave_type', name='uq_leave_policies_company_id')
    )
    op.create_index(op.f('ix_leave_policies_company_id'), 'leave_policies', ['company_id'], unique=False)
    op.create_table('saved_views',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_saved_views_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_saved_views_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_views'))
    )
    op.create_index(op.f('ix_saved_views_company_id'), 'saved_views', ['company_id'], unique=False)
    op.create_index('ix_saved_views_entity', 'saved_views', ['company_id', 'entity'], unique=False)
    op.create_index(op.f('ix_saved_views_owner_id'), 'saved_views', ['owner_id'], unique=False)
    op.create_table('project_checkins',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('health', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('highlights', sa.Text(), nullable=True),
    sa.Column('risks', sa.Text(), nullable=True),
    sa.Column('next_steps', sa.Text(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_project_checkins_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_project_checkins_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_checkins_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_checkins'))
    )
    op.create_index(op.f('ix_project_checkins_company_id'), 'project_checkins', ['company_id'], unique=False)
    op.create_index(op.f('ix_project_checkins_project_id'), 'project_checkins', ['project_id'], unique=False)
    op.create_table('recurring_transactions',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('cadence', sa.String(length=16), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('next_run', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_posted_on', sa.Date(), nullable=True),
    sa.Column('posted_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['finance_accounts.id'], name=op.f('fk_recurring_transactions_account_id_finance_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['finance_categories.id'], name=op.f('fk_recurring_transactions_category_id_finance_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_recurring_transactions_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['crm_companies.id'], name=op.f('fk_recurring_transactions_customer_id_crm_companies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_recurring_transactions_project_id_projects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_recurring_transactions_vendor_id_vendors'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recurring_transactions'))
    )
    op.create_index(op.f('ix_recurring_transactions_company_id'), 'recurring_transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_recurring_transactions_next_run'), 'recurring_transactions', ['next_run'], unique=False)
    op.add_column('crm_deals', sa.Column('next_step', sa.String(length=300), nullable=True))
    op.add_column('crm_deals', sa.Column('next_step_due', sa.Date(), nullable=True))
    op.add_column('crm_deals', sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_crm_deals_next_step_due'), 'crm_deals', ['next_step_due'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crm_deals_next_step_due'), table_name='crm_deals')
    op.drop_column('crm_deals', 'last_activity_at')
    op.drop_column('crm_deals', 'next_step_due')
    op.drop_column('crm_deals', 'next_step')
    op.drop_index(op.f('ix_recurring_transactions_next_run'), table_name='recurring_transactions')
    op.drop_index(op.f('ix_recurring_transactions_company_id'), table_name='recurring_transactions')
    op.drop_table('recurring_transactions')
    op.drop_index(op.f('ix_project_checkins_project_id'), table_name='project_checkins')
    op.drop_index(op.f('ix_project_checkins_company_id'), table_name='project_checkins')
    op.drop_table('project_checkins')
    op.drop_index(op.f('ix_saved_views_owner_id'), table_name='saved_views')
    op.drop_index('ix_saved_views_entity', table_name='saved_views')
    op.drop_index(op.f('ix_saved_views_company_id'), table_name='saved_views')
    op.drop_table('saved_views')
    op.drop_index(op.f('ix_leave_policies_company_id'), table_name='leave_policies')
    op.drop_table('leave_policies')
    op.drop_index(op.f('ix_leave_adjustments_user_id'), table_name='leave_adjustments')
    op.drop_index(op.f('ix_leave_adjustments_company_id'), table_name='leave_adjustments')
    op.drop_table('leave_adjustments')
    # ### end Alembic commands ###
