"""Customer tickets, the portal login, and uptime monitoring

Revision ID: e5cddd64f9da
Revises: 0004_daily_loops
Create Date: 2026-09-12 19:08:28.299624
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0005_support'
down_revision: str | None = '0004_daily_loops'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitors',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('crm_company_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('url', sa.String(length=600), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('expected_status', sa.Integer(), nullable=False),
    sa.Column('expected_body', sa.String(length=300), nullable=True),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('failure_threshold', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=400), nullable=True),
    sa.Column('last_response_ms', sa.Integer(), nullable=True),
    sa.Column('total_checks', sa.Integer(), nullable=False),
    sa.Column('failed_checks', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_monitors_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['crm_company_id'], ['crm_companies.id'], name=op.f('fk_monitors_crm_company_id_crm_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monitors'))
    )
    op.create_index(op.f('ix_monitors_company_id'), 'monitors', ['company_id'], unique=False)
    op.create_index(op.f('ix_monitors_crm_company_id'), 'monitors', ['crm_company_id'], unique=False)
    op.create_index(op.f('ix_monitors_next_check_at'), 'monitors', ['next_check_at'], unique=False)
    op.create_table('monitor_checks',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('monitor_id', sa.UUID(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(length=400), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_monitor_checks_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('fk_monitor_checks_monitor_id_monitors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monitor_checks'))
    )
    op.create_index(op.f('ix_monitor_checks_company_id'), 'monitor_checks', ['company_id'], unique=False)
    op.create_index(op.f('ix_monitor_checks_monitor_id'), 'monitor_checks', ['monitor_id'], unique=False)
    op.create_index('ix_monitor_checks_monitor_time', 'monitor_checks', ['monitor_id', 'created_at'], unique=False)
    op.create_table('tickets',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('crm_company_id', sa.UUID(), nullable=True),
    sa.Column('requester_id', sa.UUID(), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('response_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_response_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reopened_count', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('monitor_id', sa.UUID(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('satisfaction', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name=op.f('fk_tickets_assignee_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_tickets_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['crm_company_id'], ['crm_companies.id'], name=op.f('fk_tickets_crm_company_id_crm_companies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('fk_tickets_monitor_id_monitors'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_tickets_project_id_projects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name=op.f('fk_tickets_requester_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_tickets_task_id_tasks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets')),
    sa.UniqueConstraint('company_id', 'number', name='uq_tickets_company_id')
    )
    op.create_index(op.f('ix_tickets_assignee_id'), 'tickets', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_tickets_company_id'), 'tickets', ['company_id'], unique=False)
    op.create_index('ix_tickets_company_status', 'tickets', ['company_id', 'status'], unique=False)
    op.create_index(op.f('ix_tickets_crm_company_id'), 'tickets', ['crm_company_id'], unique=False)
    op.create_index(op.f('ix_tickets_number'), 'tickets', ['number'], unique=False)
    op.create_index(op.f('ix_tickets_priority'), 'tickets', ['priority'], unique=False)
    op.create_index(op.f('ix_tickets_project_id'), 'tickets', ['project_id'], unique=False)
    op.create_index(op.f('ix_tickets_requester_id'), 'tickets', ['requester_id'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_table('monitor_incidents',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('monitor_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('cause', sa.String(length=400), nullable=True),
    sa.Column('ticket_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_monitor_incidents_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('fk_monitor_incidents_monitor_id_monitors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_monitor_incidents_ticket_id_tickets'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monitor_incidents'))
    )
    op.create_index(op.f('ix_monitor_incidents_company_id'), 'monitor_incidents', ['company_id'], unique=False)
    op.create_index(op.f('ix_monitor_incidents_monitor_id'), 'monitor_incidents', ['monitor_id'], unique=False)
    op.create_table('ticket_messages',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('is_from_customer', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_ticket_messages_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_ticket_messages_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_ticket_messages_ticket_id_tickets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_messages'))
    )
    op.create_index(op.f('ix_ticket_messages_company_id'), 'ticket_messages', ['company_id'], unique=False)
    op.create_index(op.f('ix_ticket_messages_ticket_id'), 'ticket_messages', ['ticket_id'], unique=False)
    op.add_column('users', sa.Column('crm_company_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('weekly_capacity_hours', sa.Numeric(precision=5, scale=1), nullable=False, server_default='40'))
    op.create_index(op.f('ix_users_crm_company_id'), 'users', ['crm_company_id'], unique=False)
    op.create_foreign_key(op.f('fk_users_crm_company_id_crm_companies'), 'users', 'crm_companies', ['crm_company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_crm_company_id_crm_companies'), 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_crm_company_id'), table_name='users')
    op.drop_column('users', 'weekly_capacity_hours')
    op.drop_column('users', 'crm_company_id')
    op.drop_index(op.f('ix_ticket_messages_ticket_id'), table_name='ticket_messages')
    op.drop_index(op.f('ix_ticket_messages_company_id'), table_name='ticket_messages')
    op.drop_table('ticket_messages')
    op.drop_index(op.f('ix_monitor_incidents_monitor_id'), table_name='monitor_incidents')
    op.drop_index(op.f('ix_monitor_incidents_company_id'), table_name='monitor_incidents')
    op.drop_table('monitor_incidents')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_requester_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_project_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_priority'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_number'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_crm_company_id'), table_name='tickets')
    op.drop_index('ix_tickets_company_status', table_name='tickets')
    op.drop_index(op.f('ix_tickets_company_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_assignee_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index('ix_monitor_checks_monitor_time', table_name='monitor_checks')
    op.drop_index(op.f('ix_monitor_checks_monitor_id'), table_name='monitor_checks')
    op.drop_index(op.f('ix_monitor_checks_company_id'), table_name='monitor_checks')
    op.drop_table('monitor_checks')
    op.drop_index(op.f('ix_monitors_next_check_at'), table_name='monitors')
    op.drop_index(op.f('ix_monitors_crm_company_id'), table_name='monitors')
    op.drop_index(op.f('ix_monitors_company_id'), table_name='monitors')
    op.drop_table('monitors')
    # ### end Alembic commands ###
